name: Release-Test

on:
  push:
    tags:
      - "**"
    branches: main

jobs:
  ReleaseIt:
    name: "My Release"

    runs-on: ubuntu-latest

    needs: BuildIt

    steps:
      - name: "Step 1"
        echo "Step 1"
    